### ISSUE TITLE
error while launching python virtual env

### ISSUE THREAD

**Issue by ncelectronico** [izak/ib.bluelantern#1] opened 2017-08-30 06:04 UTC
Hello,
I'm trying to install with a MK2 interface (Multiplus device) on Ubuntu 16.04
When I need to launch python vitual env, I get :

> $ venv/bin/pserve development.ini
ib.victron package not available
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/nico/git/ib.bluelantern/src/ib/bluelantern/victron/mk2.py", line 50, in <lambda>
    instance, name, serial_port)
  File "/home/nico/git/ib.bluelantern/src/ib/bluelantern/victron/mk2.py", line 12, in main
    from serial import Serial
ImportError: No module named serial
Traceback (most recent call last):
  File "venv/bin/pserve", line 11, in <module>
    sys.exit(main())
  File "/home/nico/git/ib.bluelantern/venv/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/home/nico/git/ib.bluelantern/venv/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 229, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/home/nico/git/ib.bluelantern/venv/local/lib/python2.7/site-packages/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/home/nico/git/ib.bluelantern/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/nico/git/ib.bluelantern/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/nico/git/ib.bluelantern/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/nico/git/ib.bluelantern/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/nico/git/ib.bluelantern/venv/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/nico/git/ib.bluelantern/src/ib/bluelantern/__init__.py", line 16, in main
    config.scan()
  File "/home/nico/git/ib.bluelantern/venv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 1043, in scan
    ignore=ignore)
  File "/home/nico/git/ib.bluelantern/venv/local/lib/python2.7/site-packages/venusian/__init__.py", line 230, in scan
    __import__(modname)
  File "/home/nico/git/ib.bluelantern/src/ib/bluelantern/victron/vedirect.py", line 3, in <module>
    from serial import Serial
ImportError: No module named serial

Before trying bluelantern, I've installed ib.victron and it works as expected :

> $ monitor
Time            2017-08-30 16:49
Inverter mode     Charge storage
Mains Voltage     229.73 V
AC output Voltage 229.73 V
Battery Voltage   13.29 V
Discharge current 0.0 A
DC Power draw     0.0 W
AC Power draw     55.1352 VA

May you assist with this ?
Thanks in advance for your time.

**Comment by izak** [comment] 2017-09-11 07:50
I didn't realise people were still attempting to use this. This is mostly an abandoned project, because I instead invested my time in working on bringing Venus itself (Victron's firmware for the CCGX) to the Raspberry Pi. So you really should rather look into running Venus itself on a small board computer rather than this project.

If you still want to, you need to install pyserial. It should be as easy as:

    sudo apt-get install python-serial

Or alternatively:

    venv/bin/pip install pyserial

I have not tested it with newer versions of pyserial, so you may even have to install an older one, eg:

    venv/bin/pip install pyserial==3.2.1

Also, it looks like you need to install ib.victron inside the virtualenv. The very first line indicates it is not available (though that might be because of the missing pyserial).

In any case, this is not a bug but a missing dependency, so I'm closing this issue.

**Closed as completed by izak** 2017-09-11 07:50 UTC
